// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview A flow to dynamically generate a background based on weather conditions using generative AI.
 *
 * - generateWeatherBackground - A function that generates a weather-based background.
 * - GenerateWeatherBackgroundInput - The input type for the generateWeatherBackground function.
 * - GenerateWeatherBackgroundOutput - The return type for the generateWeatherBackground function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateWeatherBackgroundInputSchema = z.object({
  weatherCondition: z
    .string()
    .describe('The current weather condition (e.g., sunny, rainy, cloudy).'),
});
export type GenerateWeatherBackgroundInput = z.infer<
  typeof GenerateWeatherBackgroundInputSchema
>;

const GenerateWeatherBackgroundOutputSchema = z.object({
  backgroundImageUrl: z
    .string()
    .describe(
      'The URL of the generated background image, as a data URI that must include a MIME type and use Base64 encoding. Expected format: \'data:<mimetype>;base64,<encoded_data>\'.'      
    ),
});
export type GenerateWeatherBackgroundOutput = z.infer<
  typeof GenerateWeatherBackgroundOutputSchema
>;

export async function generateWeatherBackground(
  input: GenerateWeatherBackgroundInput
): Promise<GenerateWeatherBackgroundOutput> {
  return generateWeatherBackgroundFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateWeatherBackgroundPrompt',
  input: {schema: GenerateWeatherBackgroundInputSchema},
  output: {schema: GenerateWeatherBackgroundOutputSchema},
  prompt: `Generate a visually appealing background image URL based on the following weather condition:\n\nWeather Condition: {{{weatherCondition}}}\n\nThe background image should be contextually relevant to the weather condition. The image URL should be a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'.`,
});

const generateWeatherBackgroundFlow = ai.defineFlow(
  {
    name: 'generateWeatherBackgroundFlow',
    inputSchema: GenerateWeatherBackgroundInputSchema,
    outputSchema: GenerateWeatherBackgroundOutputSchema,
  },
  async input => {
    const {media} = await ai.generate({
      model: 'googleai/imagen-4.0-fast-generate-001',
      prompt: `Generate a background image reflecting ${input.weatherCondition} weather.`,      
    });

    if (!media || !media.url) {
      throw new Error('Failed to generate background image.');
    }

    return {backgroundImageUrl: media.url};
  }
);
